services:
  backend:
    build: ./ai-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    command: node automationWorker.js
    volumes:
      # - ./backend:/app
      # ensure container’s own node_modules stays, not your Windows copy:
      - backend_node_modules:/app/node_modules
      - ./backend/logs.db:/app/logs.db
      - ./backend/debug_logs:/app/debug_logs
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  backend_node_modules: